<?php
return array(
'ABeeZee'=>array('family'=>'ABeeZee','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'Abel'=>array('family'=>'Abel','variants'=>array('regular'),'subsets'=>array('latin')),
'Abril_Fatface'=>array('family'=>'Abril Fatface','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Aclonica'=>array('family'=>'Aclonica','variants'=>array('regular'),'subsets'=>array('latin')),
'Acme'=>array('family'=>'Acme','variants'=>array('regular'),'subsets'=>array('latin')),
'Actor'=>array('family'=>'Actor','variants'=>array('regular'),'subsets'=>array('latin')),
'Adamina'=>array('family'=>'Adamina','variants'=>array('regular'),'subsets'=>array('latin')),
'Advent_Pro'=>array('family'=>'Advent Pro','variants'=>array('100','200','300','regular','500','600','700'),'subsets'=>array('latin-ext','greek','latin')),
'Aguafina_Script'=>array('family'=>'Aguafina Script','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Akronim'=>array('family'=>'Akronim','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Aladin'=>array('family'=>'Aladin','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Aldrich'=>array('family'=>'Aldrich','variants'=>array('regular'),'subsets'=>array('latin')),
'Alef'=>array('family'=>'Alef','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Alegreya'=>array('family'=>'Alegreya','variants'=>array('regular','italic','700','700italic','900','900italic'),'subsets'=>array('latin-ext','latin')),
'Alegreya_SC'=>array('family'=>'Alegreya SC','variants'=>array('regular','italic','700','700italic','900','900italic'),'subsets'=>array('latin-ext','latin')),
'Alegreya_Sans'=>array('family'=>'Alegreya Sans','variants'=>array('100','100italic','300','300italic','regular','italic','500','500italic','700','700italic','800','800italic','900','900italic'),'subsets'=>array('vietnamese','latin-ext','latin')),
'Alegreya_Sans_SC'=>array('family'=>'Alegreya Sans SC','variants'=>array('100','100italic','300','300italic','regular','italic','500','500italic','700','700italic','800','800italic','900','900italic'),'subsets'=>array('vietnamese','latin-ext','latin')),
'Alex_Brush'=>array('family'=>'Alex Brush','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Alfa_Slab_One'=>array('family'=>'Alfa Slab One','variants'=>array('regular'),'subsets'=>array('latin')),
'Alice'=>array('family'=>'Alice','variants'=>array('regular'),'subsets'=>array('latin')),
'Alike'=>array('family'=>'Alike','variants'=>array('regular'),'subsets'=>array('latin')),
'Alike_Angular'=>array('family'=>'Alike Angular','variants'=>array('regular'),'subsets'=>array('latin')),
'Allan'=>array('family'=>'Allan','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Allerta'=>array('family'=>'Allerta','variants'=>array('regular'),'subsets'=>array('latin')),
'Allerta_Stencil'=>array('family'=>'Allerta Stencil','variants'=>array('regular'),'subsets'=>array('latin')),
'Allura'=>array('family'=>'Allura','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Almendra'=>array('family'=>'Almendra','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Almendra_Display'=>array('family'=>'Almendra Display','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Almendra_SC'=>array('family'=>'Almendra SC','variants'=>array('regular'),'subsets'=>array('latin')),
'Amarante'=>array('family'=>'Amarante','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Amaranth'=>array('family'=>'Amaranth','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Amatic_SC'=>array('family'=>'Amatic SC','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Amethysta'=>array('family'=>'Amethysta','variants'=>array('regular'),'subsets'=>array('latin')),
'Anaheim'=>array('family'=>'Anaheim','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Andada'=>array('family'=>'Andada','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Andika'=>array('family'=>'Andika','variants'=>array('regular'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'Angkor'=>array('family'=>'Angkor','variants'=>array('regular'),'subsets'=>array('khmer')),
'Annie_Use_Your_Telescope'=>array('family'=>'Annie Use Your Telescope','variants'=>array('regular'),'subsets'=>array('latin')),
'Anonymous_Pro'=>array('family'=>'Anonymous Pro','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','greek','cyrillic','latin')),
'Antic'=>array('family'=>'Antic','variants'=>array('regular'),'subsets'=>array('latin')),
'Antic_Didone'=>array('family'=>'Antic Didone','variants'=>array('regular'),'subsets'=>array('latin')),
'Antic_Slab'=>array('family'=>'Antic Slab','variants'=>array('regular'),'subsets'=>array('latin')),
'Anton'=>array('family'=>'Anton','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Arapey'=>array('family'=>'Arapey','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'Arbutus'=>array('family'=>'Arbutus','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Arbutus_Slab'=>array('family'=>'Arbutus Slab','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Architects_Daughter'=>array('family'=>'Architects Daughter','variants'=>array('regular'),'subsets'=>array('latin')),
'Archivo_Black'=>array('family'=>'Archivo Black','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Archivo_Narrow'=>array('family'=>'Archivo Narrow','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Arimo'=>array('family'=>'Arimo','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Arizonia'=>array('family'=>'Arizonia','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Armata'=>array('family'=>'Armata','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Artifika'=>array('family'=>'Artifika','variants'=>array('regular'),'subsets'=>array('latin')),
'Arvo'=>array('family'=>'Arvo','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Asap'=>array('family'=>'Asap','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Asset'=>array('family'=>'Asset','variants'=>array('regular'),'subsets'=>array('latin')),
'Astloch'=>array('family'=>'Astloch','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Asul'=>array('family'=>'Asul','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Atomic_Age'=>array('family'=>'Atomic Age','variants'=>array('regular'),'subsets'=>array('latin')),
'Aubrey'=>array('family'=>'Aubrey','variants'=>array('regular'),'subsets'=>array('latin')),
'Audiowide'=>array('family'=>'Audiowide','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Autour_One'=>array('family'=>'Autour One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Average'=>array('family'=>'Average','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Average_Sans'=>array('family'=>'Average Sans','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Averia_Gruesa_Libre'=>array('family'=>'Averia Gruesa Libre','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Averia_Libre'=>array('family'=>'Averia Libre','variants'=>array('300','300italic','regular','italic','700','700italic'),'subsets'=>array('latin')),
'Averia_Sans_Libre'=>array('family'=>'Averia Sans Libre','variants'=>array('300','300italic','regular','italic','700','700italic'),'subsets'=>array('latin')),
'Averia_Serif_Libre'=>array('family'=>'Averia Serif Libre','variants'=>array('300','300italic','regular','italic','700','700italic'),'subsets'=>array('latin')),
'Bad_Script'=>array('family'=>'Bad Script','variants'=>array('regular'),'subsets'=>array('cyrillic','latin')),
'Balthazar'=>array('family'=>'Balthazar','variants'=>array('regular'),'subsets'=>array('latin')),
'Bangers'=>array('family'=>'Bangers','variants'=>array('regular'),'subsets'=>array('latin')),
'Basic'=>array('family'=>'Basic','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Battambang'=>array('family'=>'Battambang','variants'=>array('regular','700'),'subsets'=>array('khmer')),
'Baumans'=>array('family'=>'Baumans','variants'=>array('regular'),'subsets'=>array('latin')),
'Bayon'=>array('family'=>'Bayon','variants'=>array('regular'),'subsets'=>array('khmer')),
'Belgrano'=>array('family'=>'Belgrano','variants'=>array('regular'),'subsets'=>array('latin')),
'Belleza'=>array('family'=>'Belleza','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'BenchNine'=>array('family'=>'BenchNine','variants'=>array('300','regular','700'),'subsets'=>array('latin-ext','latin')),
'Bentham'=>array('family'=>'Bentham','variants'=>array('regular'),'subsets'=>array('latin')),
'Berkshire_Swash'=>array('family'=>'Berkshire Swash','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Bevan'=>array('family'=>'Bevan','variants'=>array('regular'),'subsets'=>array('latin')),
'Bigelow_Rules'=>array('family'=>'Bigelow Rules','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Bigshot_One'=>array('family'=>'Bigshot One','variants'=>array('regular'),'subsets'=>array('latin')),
'Bilbo'=>array('family'=>'Bilbo','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Bilbo_Swash_Caps'=>array('family'=>'Bilbo Swash Caps','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Bitter'=>array('family'=>'Bitter','variants'=>array('regular','italic','700'),'subsets'=>array('latin-ext','latin')),
'Black_Ops_One'=>array('family'=>'Black Ops One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Bokor'=>array('family'=>'Bokor','variants'=>array('regular'),'subsets'=>array('khmer')),
'Bonbon'=>array('family'=>'Bonbon','variants'=>array('regular'),'subsets'=>array('latin')),
'Boogaloo'=>array('family'=>'Boogaloo','variants'=>array('regular'),'subsets'=>array('latin')),
'Bowlby_One'=>array('family'=>'Bowlby One','variants'=>array('regular'),'subsets'=>array('latin')),
'Bowlby_One_SC'=>array('family'=>'Bowlby One SC','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Brawler'=>array('family'=>'Brawler','variants'=>array('regular'),'subsets'=>array('latin')),
'Bree_Serif'=>array('family'=>'Bree Serif','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Bubblegum_Sans'=>array('family'=>'Bubblegum Sans','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Bubbler_One'=>array('family'=>'Bubbler One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Buda'=>array('family'=>'Buda','variants'=>array('300'),'subsets'=>array('latin')),
'Buenard'=>array('family'=>'Buenard','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Butcherman'=>array('family'=>'Butcherman','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Butterfly_Kids'=>array('family'=>'Butterfly Kids','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Cabin'=>array('family'=>'Cabin','variants'=>array('regular','italic','500','500italic','600','600italic','700','700italic'),'subsets'=>array('latin')),
'Cabin_Condensed'=>array('family'=>'Cabin Condensed','variants'=>array('regular','500','600','700'),'subsets'=>array('latin')),
'Cabin_Sketch'=>array('family'=>'Cabin Sketch','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Caesar_Dressing'=>array('family'=>'Caesar Dressing','variants'=>array('regular'),'subsets'=>array('latin')),
'Cagliostro'=>array('family'=>'Cagliostro','variants'=>array('regular'),'subsets'=>array('latin')),
'Calligraffitti'=>array('family'=>'Calligraffitti','variants'=>array('regular'),'subsets'=>array('latin')),
'Cambo'=>array('family'=>'Cambo','variants'=>array('regular'),'subsets'=>array('latin')),
'Candal'=>array('family'=>'Candal','variants'=>array('regular'),'subsets'=>array('latin')),
'Cantarell'=>array('family'=>'Cantarell','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Cantata_One'=>array('family'=>'Cantata One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Cantora_One'=>array('family'=>'Cantora One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Capriola'=>array('family'=>'Capriola','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Cardo'=>array('family'=>'Cardo','variants'=>array('regular','italic','700'),'subsets'=>array('latin-ext','greek','greek-ext','latin')),
'Carme'=>array('family'=>'Carme','variants'=>array('regular'),'subsets'=>array('latin')),
'Carrois_Gothic'=>array('family'=>'Carrois Gothic','variants'=>array('regular'),'subsets'=>array('latin')),
'Carrois_Gothic_SC'=>array('family'=>'Carrois Gothic SC','variants'=>array('regular'),'subsets'=>array('latin')),
'Carter_One'=>array('family'=>'Carter One','variants'=>array('regular'),'subsets'=>array('latin')),
'Caudex'=>array('family'=>'Caudex','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','greek','greek-ext','latin')),
'Cedarville_Cursive'=>array('family'=>'Cedarville Cursive','variants'=>array('regular'),'subsets'=>array('latin')),
'Ceviche_One'=>array('family'=>'Ceviche One','variants'=>array('regular'),'subsets'=>array('latin')),
'Changa_One'=>array('family'=>'Changa One','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'Chango'=>array('family'=>'Chango','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Chau_Philomene_One'=>array('family'=>'Chau Philomene One','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Chela_One'=>array('family'=>'Chela One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Chelsea_Market'=>array('family'=>'Chelsea Market','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Chenla'=>array('family'=>'Chenla','variants'=>array('regular'),'subsets'=>array('khmer')),
'Cherry_Cream_Soda'=>array('family'=>'Cherry Cream Soda','variants'=>array('regular'),'subsets'=>array('latin')),
'Cherry_Swash'=>array('family'=>'Cherry Swash','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Chewy'=>array('family'=>'Chewy','variants'=>array('regular'),'subsets'=>array('latin')),
'Chicle'=>array('family'=>'Chicle','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Chivo'=>array('family'=>'Chivo','variants'=>array('regular','italic','900','900italic'),'subsets'=>array('latin')),
'Cinzel'=>array('family'=>'Cinzel','variants'=>array('regular','700','900'),'subsets'=>array('latin')),
'Cinzel_Decorative'=>array('family'=>'Cinzel Decorative','variants'=>array('regular','700','900'),'subsets'=>array('latin')),
'Clicker_Script'=>array('family'=>'Clicker Script','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Coda'=>array('family'=>'Coda','variants'=>array('regular','800'),'subsets'=>array('latin')),
'Coda_Caption'=>array('family'=>'Coda Caption','variants'=>array('800'),'subsets'=>array('latin')),
'Codystar'=>array('family'=>'Codystar','variants'=>array('300','regular'),'subsets'=>array('latin-ext','latin')),
'Combo'=>array('family'=>'Combo','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Comfortaa'=>array('family'=>'Comfortaa','variants'=>array('300','regular','700'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','latin')),
'Coming_Soon'=>array('family'=>'Coming Soon','variants'=>array('regular'),'subsets'=>array('latin')),
'Concert_One'=>array('family'=>'Concert One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Condiment'=>array('family'=>'Condiment','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Content'=>array('family'=>'Content','variants'=>array('regular','700'),'subsets'=>array('khmer')),
'Contrail_One'=>array('family'=>'Contrail One','variants'=>array('regular'),'subsets'=>array('latin')),
'Convergence'=>array('family'=>'Convergence','variants'=>array('regular'),'subsets'=>array('latin')),
'Cookie'=>array('family'=>'Cookie','variants'=>array('regular'),'subsets'=>array('latin')),
'Copse'=>array('family'=>'Copse','variants'=>array('regular'),'subsets'=>array('latin')),
'Corben'=>array('family'=>'Corben','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Courgette'=>array('family'=>'Courgette','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Cousine'=>array('family'=>'Cousine','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Coustard'=>array('family'=>'Coustard','variants'=>array('regular','900'),'subsets'=>array('latin')),
'Covered_By_Your_Grace'=>array('family'=>'Covered By Your Grace','variants'=>array('regular'),'subsets'=>array('latin')),
'Crafty_Girls'=>array('family'=>'Crafty Girls','variants'=>array('regular'),'subsets'=>array('latin')),
'Creepster'=>array('family'=>'Creepster','variants'=>array('regular'),'subsets'=>array('latin')),
'Crete_Round'=>array('family'=>'Crete Round','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Crimson_Text'=>array('family'=>'Crimson Text','variants'=>array('regular','italic','600','600italic','700','700italic'),'subsets'=>array('latin')),
'Croissant_One'=>array('family'=>'Croissant One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Crushed'=>array('family'=>'Crushed','variants'=>array('regular'),'subsets'=>array('latin')),
'Cuprum'=>array('family'=>'Cuprum','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Cutive'=>array('family'=>'Cutive','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Cutive_Mono'=>array('family'=>'Cutive Mono','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Damion'=>array('family'=>'Damion','variants'=>array('regular'),'subsets'=>array('latin')),
'Dancing_Script'=>array('family'=>'Dancing Script','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Dangrek'=>array('family'=>'Dangrek','variants'=>array('regular'),'subsets'=>array('khmer')),
'Dawning_of_a_New_Day'=>array('family'=>'Dawning of a New Day','variants'=>array('regular'),'subsets'=>array('latin')),
'Days_One'=>array('family'=>'Days One','variants'=>array('regular'),'subsets'=>array('latin')),
'Delius'=>array('family'=>'Delius','variants'=>array('regular'),'subsets'=>array('latin')),
'Delius_Swash_Caps'=>array('family'=>'Delius Swash Caps','variants'=>array('regular'),'subsets'=>array('latin')),
'Delius_Unicase'=>array('family'=>'Delius Unicase','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Della_Respira'=>array('family'=>'Della Respira','variants'=>array('regular'),'subsets'=>array('latin')),
'Denk_One'=>array('family'=>'Denk One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Devonshire'=>array('family'=>'Devonshire','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Didact_Gothic'=>array('family'=>'Didact Gothic','variants'=>array('regular'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Diplomata'=>array('family'=>'Diplomata','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Diplomata_SC'=>array('family'=>'Diplomata SC','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Domine'=>array('family'=>'Domine','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Donegal_One'=>array('family'=>'Donegal One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Doppio_One'=>array('family'=>'Doppio One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Dorsa'=>array('family'=>'Dorsa','variants'=>array('regular'),'subsets'=>array('latin')),
'Dosis'=>array('family'=>'Dosis','variants'=>array('200','300','regular','500','600','700','800'),'subsets'=>array('latin-ext','latin')),
'Dr_Sugiyama'=>array('family'=>'Dr Sugiyama','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Droid_Sans'=>array('family'=>'Droid Sans','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Droid_Sans_Mono'=>array('family'=>'Droid Sans Mono','variants'=>array('regular'),'subsets'=>array('latin')),
'Droid_Serif'=>array('family'=>'Droid Serif','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Duru_Sans'=>array('family'=>'Duru Sans','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Dynalight'=>array('family'=>'Dynalight','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'EB_Garamond'=>array('family'=>'EB Garamond','variants'=>array('regular'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','cyrillic','latin')),
'Eagle_Lake'=>array('family'=>'Eagle Lake','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Eater'=>array('family'=>'Eater','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Economica'=>array('family'=>'Economica','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Ek_Mukta'=>array('family'=>'Ek Mukta','variants'=>array('200','300','regular','500','600','700','800'),'subsets'=>array('latin-ext','devanagari','latin')),
'Electrolize'=>array('family'=>'Electrolize','variants'=>array('regular'),'subsets'=>array('latin')),
'Elsie'=>array('family'=>'Elsie','variants'=>array('regular','900'),'subsets'=>array('latin-ext','latin')),
'Elsie_Swash_Caps'=>array('family'=>'Elsie Swash Caps','variants'=>array('regular','900'),'subsets'=>array('latin-ext','latin')),
'Emblema_One'=>array('family'=>'Emblema One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Emilys_Candy'=>array('family'=>'Emilys Candy','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Engagement'=>array('family'=>'Engagement','variants'=>array('regular'),'subsets'=>array('latin')),
'Englebert'=>array('family'=>'Englebert','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Enriqueta'=>array('family'=>'Enriqueta','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Erica_One'=>array('family'=>'Erica One','variants'=>array('regular'),'subsets'=>array('latin')),
'Esteban'=>array('family'=>'Esteban','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Euphoria_Script'=>array('family'=>'Euphoria Script','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ewert'=>array('family'=>'Ewert','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Exo'=>array('family'=>'Exo','variants'=>array('100','100italic','200','200italic','300','300italic','regular','italic','500','500italic','600','600italic','700','700italic','800','800italic','900','900italic'),'subsets'=>array('latin-ext','latin')),
'Exo_2'=>array('family'=>'Exo 2','variants'=>array('100','100italic','200','200italic','300','300italic','regular','italic','500','500italic','600','600italic','700','700italic','800','800italic','900','900italic'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Expletus_Sans'=>array('family'=>'Expletus Sans','variants'=>array('regular','italic','500','500italic','600','600italic','700','700italic'),'subsets'=>array('latin')),
'Fanwood_Text'=>array('family'=>'Fanwood Text','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'Fascinate'=>array('family'=>'Fascinate','variants'=>array('regular'),'subsets'=>array('latin')),
'Fascinate_Inline'=>array('family'=>'Fascinate Inline','variants'=>array('regular'),'subsets'=>array('latin')),
'Faster_One'=>array('family'=>'Faster One','variants'=>array('regular'),'subsets'=>array('latin')),
'Fasthand'=>array('family'=>'Fasthand','variants'=>array('regular'),'subsets'=>array('khmer')),
'Fauna_One'=>array('family'=>'Fauna One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Federant'=>array('family'=>'Federant','variants'=>array('regular'),'subsets'=>array('latin')),
'Federo'=>array('family'=>'Federo','variants'=>array('regular'),'subsets'=>array('latin')),
'Felipa'=>array('family'=>'Felipa','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Fenix'=>array('family'=>'Fenix','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Finger_Paint'=>array('family'=>'Finger Paint','variants'=>array('regular'),'subsets'=>array('latin')),
'Fira_Mono'=>array('family'=>'Fira Mono','variants'=>array('regular','700'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','latin')),
'Fira_Sans'=>array('family'=>'Fira Sans','variants'=>array('300','300italic','regular','italic','500','500italic','700','700italic'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','latin')),
'Fjalla_One'=>array('family'=>'Fjalla One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Fjord_One'=>array('family'=>'Fjord One','variants'=>array('regular'),'subsets'=>array('latin')),
'Flamenco'=>array('family'=>'Flamenco','variants'=>array('300','regular'),'subsets'=>array('latin')),
'Flavors'=>array('family'=>'Flavors','variants'=>array('regular'),'subsets'=>array('latin')),
'Fondamento'=>array('family'=>'Fondamento','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Fontdiner_Swanky'=>array('family'=>'Fontdiner Swanky','variants'=>array('regular'),'subsets'=>array('latin')),
'Forum'=>array('family'=>'Forum','variants'=>array('regular'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'Francois_One'=>array('family'=>'Francois One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Freckle_Face'=>array('family'=>'Freckle Face','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Fredericka_the_Great'=>array('family'=>'Fredericka the Great','variants'=>array('regular'),'subsets'=>array('latin')),
'Fredoka_One'=>array('family'=>'Fredoka One','variants'=>array('regular'),'subsets'=>array('latin')),
'Freehand'=>array('family'=>'Freehand','variants'=>array('regular'),'subsets'=>array('khmer')),
'Fresca'=>array('family'=>'Fresca','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Frijole'=>array('family'=>'Frijole','variants'=>array('regular'),'subsets'=>array('latin')),
'Fruktur'=>array('family'=>'Fruktur','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Fugaz_One'=>array('family'=>'Fugaz One','variants'=>array('regular'),'subsets'=>array('latin')),
'GFS_Didot'=>array('family'=>'GFS Didot','variants'=>array('regular'),'subsets'=>array('greek')),
'GFS_Neohellenic'=>array('family'=>'GFS Neohellenic','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('greek')),
'Gabriela'=>array('family'=>'Gabriela','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Gafata'=>array('family'=>'Gafata','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Galdeano'=>array('family'=>'Galdeano','variants'=>array('regular'),'subsets'=>array('latin')),
'Galindo'=>array('family'=>'Galindo','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Gentium_Basic'=>array('family'=>'Gentium Basic','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Gentium_Book_Basic'=>array('family'=>'Gentium Book Basic','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Geo'=>array('family'=>'Geo','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'Geostar'=>array('family'=>'Geostar','variants'=>array('regular'),'subsets'=>array('latin')),
'Geostar_Fill'=>array('family'=>'Geostar Fill','variants'=>array('regular'),'subsets'=>array('latin')),
'Germania_One'=>array('family'=>'Germania One','variants'=>array('regular'),'subsets'=>array('latin')),
'Gilda_Display'=>array('family'=>'Gilda Display','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Give_You_Glory'=>array('family'=>'Give You Glory','variants'=>array('regular'),'subsets'=>array('latin')),
'Glass_Antiqua'=>array('family'=>'Glass Antiqua','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Glegoo'=>array('family'=>'Glegoo','variants'=>array('regular','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Gloria_Hallelujah'=>array('family'=>'Gloria Hallelujah','variants'=>array('regular'),'subsets'=>array('latin')),
'Goblin_One'=>array('family'=>'Goblin One','variants'=>array('regular'),'subsets'=>array('latin')),
'Gochi_Hand'=>array('family'=>'Gochi Hand','variants'=>array('regular'),'subsets'=>array('latin')),
'Gorditas'=>array('family'=>'Gorditas','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Goudy_Bookletter_1911'=>array('family'=>'Goudy Bookletter 1911','variants'=>array('regular'),'subsets'=>array('latin')),
'Graduate'=>array('family'=>'Graduate','variants'=>array('regular'),'subsets'=>array('latin')),
'Grand_Hotel'=>array('family'=>'Grand Hotel','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Gravitas_One'=>array('family'=>'Gravitas One','variants'=>array('regular'),'subsets'=>array('latin')),
'Great_Vibes'=>array('family'=>'Great Vibes','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Griffy'=>array('family'=>'Griffy','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Gruppo'=>array('family'=>'Gruppo','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Gudea'=>array('family'=>'Gudea','variants'=>array('regular','italic','700'),'subsets'=>array('latin-ext','latin')),
'Habibi'=>array('family'=>'Habibi','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Halant'=>array('family'=>'Halant','variants'=>array('300','regular','500','600','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Hammersmith_One'=>array('family'=>'Hammersmith One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Hanalei'=>array('family'=>'Hanalei','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Hanalei_Fill'=>array('family'=>'Hanalei Fill','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Handlee'=>array('family'=>'Handlee','variants'=>array('regular'),'subsets'=>array('latin')),
'Hanuman'=>array('family'=>'Hanuman','variants'=>array('regular','700'),'subsets'=>array('khmer')),
'Happy_Monkey'=>array('family'=>'Happy Monkey','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Headland_One'=>array('family'=>'Headland One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Henny_Penny'=>array('family'=>'Henny Penny','variants'=>array('regular'),'subsets'=>array('latin')),
'Herr_Von_Muellerhoff'=>array('family'=>'Herr Von Muellerhoff','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Hind'=>array('family'=>'Hind','variants'=>array('300','regular','500','600','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Holtwood_One_SC'=>array('family'=>'Holtwood One SC','variants'=>array('regular'),'subsets'=>array('latin')),
'Homemade_Apple'=>array('family'=>'Homemade Apple','variants'=>array('regular'),'subsets'=>array('latin')),
'Homenaje'=>array('family'=>'Homenaje','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'IM_Fell_DW_Pica'=>array('family'=>'IM Fell DW Pica','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'IM_Fell_DW_Pica_SC'=>array('family'=>'IM Fell DW Pica SC','variants'=>array('regular'),'subsets'=>array('latin')),
'IM_Fell_Double_Pica'=>array('family'=>'IM Fell Double Pica','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'IM_Fell_Double_Pica_SC'=>array('family'=>'IM Fell Double Pica SC','variants'=>array('regular'),'subsets'=>array('latin')),
'IM_Fell_English'=>array('family'=>'IM Fell English','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'IM_Fell_English_SC'=>array('family'=>'IM Fell English SC','variants'=>array('regular'),'subsets'=>array('latin')),
'IM_Fell_French_Canon'=>array('family'=>'IM Fell French Canon','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'IM_Fell_French_Canon_SC'=>array('family'=>'IM Fell French Canon SC','variants'=>array('regular'),'subsets'=>array('latin')),
'IM_Fell_Great_Primer'=>array('family'=>'IM Fell Great Primer','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'IM_Fell_Great_Primer_SC'=>array('family'=>'IM Fell Great Primer SC','variants'=>array('regular'),'subsets'=>array('latin')),
'Iceberg'=>array('family'=>'Iceberg','variants'=>array('regular'),'subsets'=>array('latin')),
'Iceland'=>array('family'=>'Iceland','variants'=>array('regular'),'subsets'=>array('latin')),
'Imprima'=>array('family'=>'Imprima','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Inconsolata'=>array('family'=>'Inconsolata','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Inder'=>array('family'=>'Inder','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Indie_Flower'=>array('family'=>'Indie Flower','variants'=>array('regular'),'subsets'=>array('latin')),
'Inika'=>array('family'=>'Inika','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Irish_Grover'=>array('family'=>'Irish Grover','variants'=>array('regular'),'subsets'=>array('latin')),
'Istok_Web'=>array('family'=>'Istok Web','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'Italiana'=>array('family'=>'Italiana','variants'=>array('regular'),'subsets'=>array('latin')),
'Italianno'=>array('family'=>'Italianno','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Jacques_Francois'=>array('family'=>'Jacques Francois','variants'=>array('regular'),'subsets'=>array('latin')),
'Jacques_Francois_Shadow'=>array('family'=>'Jacques Francois Shadow','variants'=>array('regular'),'subsets'=>array('latin')),
'Jim_Nightshade'=>array('family'=>'Jim Nightshade','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Jockey_One'=>array('family'=>'Jockey One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Jolly_Lodger'=>array('family'=>'Jolly Lodger','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Josefin_Sans'=>array('family'=>'Josefin Sans','variants'=>array('100','100italic','300','300italic','regular','italic','600','600italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Josefin_Slab'=>array('family'=>'Josefin Slab','variants'=>array('100','100italic','300','300italic','regular','italic','600','600italic','700','700italic'),'subsets'=>array('latin')),
'Joti_One'=>array('family'=>'Joti One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Judson'=>array('family'=>'Judson','variants'=>array('regular','italic','700'),'subsets'=>array('latin')),
'Julee'=>array('family'=>'Julee','variants'=>array('regular'),'subsets'=>array('latin')),
'Julius_Sans_One'=>array('family'=>'Julius Sans One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Junge'=>array('family'=>'Junge','variants'=>array('regular'),'subsets'=>array('latin')),
'Jura'=>array('family'=>'Jura','variants'=>array('300','regular','500','600'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','latin')),
'Just_Another_Hand'=>array('family'=>'Just Another Hand','variants'=>array('regular'),'subsets'=>array('latin')),
'Just_Me_Again_Down_Here'=>array('family'=>'Just Me Again Down Here','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Kalam'=>array('family'=>'Kalam','variants'=>array('300','regular','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Kameron'=>array('family'=>'Kameron','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Kantumruy'=>array('family'=>'Kantumruy','variants'=>array('300','regular','700'),'subsets'=>array('khmer')),
'Karla'=>array('family'=>'Karla','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Karma'=>array('family'=>'Karma','variants'=>array('300','regular','500','600','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Kaushan_Script'=>array('family'=>'Kaushan Script','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Kavoon'=>array('family'=>'Kavoon','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Kdam_Thmor'=>array('family'=>'Kdam Thmor','variants'=>array('regular'),'subsets'=>array('khmer')),
'Keania_One'=>array('family'=>'Keania One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Kelly_Slab'=>array('family'=>'Kelly Slab','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Kenia'=>array('family'=>'Kenia','variants'=>array('regular'),'subsets'=>array('latin')),
'Khand'=>array('family'=>'Khand','variants'=>array('300','regular','500','600','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Khmer'=>array('family'=>'Khmer','variants'=>array('regular'),'subsets'=>array('khmer')),
'Kite_One'=>array('family'=>'Kite One','variants'=>array('regular'),'subsets'=>array('latin')),
'Knewave'=>array('family'=>'Knewave','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Kotta_One'=>array('family'=>'Kotta One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Koulen'=>array('family'=>'Koulen','variants'=>array('regular'),'subsets'=>array('khmer')),
'Kranky'=>array('family'=>'Kranky','variants'=>array('regular'),'subsets'=>array('latin')),
'Kreon'=>array('family'=>'Kreon','variants'=>array('300','regular','700'),'subsets'=>array('latin')),
'Kristi'=>array('family'=>'Kristi','variants'=>array('regular'),'subsets'=>array('latin')),
'Krona_One'=>array('family'=>'Krona One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'La_Belle_Aurore'=>array('family'=>'La Belle Aurore','variants'=>array('regular'),'subsets'=>array('latin')),
'Laila'=>array('family'=>'Laila','variants'=>array('300','regular','500','600','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Lancelot'=>array('family'=>'Lancelot','variants'=>array('regular'),'subsets'=>array('latin')),
'Lato'=>array('family'=>'Lato','variants'=>array('100','100italic','300','300italic','regular','italic','700','700italic','900','900italic'),'subsets'=>array('latin-ext','latin')),
'League_Script'=>array('family'=>'League Script','variants'=>array('regular'),'subsets'=>array('latin')),
'Leckerli_One'=>array('family'=>'Leckerli One','variants'=>array('regular'),'subsets'=>array('latin')),
'Ledger'=>array('family'=>'Ledger','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Lekton'=>array('family'=>'Lekton','variants'=>array('regular','italic','700'),'subsets'=>array('latin-ext','latin')),
'Lemon'=>array('family'=>'Lemon','variants'=>array('regular'),'subsets'=>array('latin')),
'Libre_Baskerville'=>array('family'=>'Libre Baskerville','variants'=>array('regular','italic','700'),'subsets'=>array('latin-ext','latin')),
'Life_Savers'=>array('family'=>'Life Savers','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Lilita_One'=>array('family'=>'Lilita One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Lily_Script_One'=>array('family'=>'Lily Script One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Limelight'=>array('family'=>'Limelight','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Linden_Hill'=>array('family'=>'Linden Hill','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'Lobster'=>array('family'=>'Lobster','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Lobster_Two'=>array('family'=>'Lobster Two','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Londrina_Outline'=>array('family'=>'Londrina Outline','variants'=>array('regular'),'subsets'=>array('latin')),
'Londrina_Shadow'=>array('family'=>'Londrina Shadow','variants'=>array('regular'),'subsets'=>array('latin')),
'Londrina_Sketch'=>array('family'=>'Londrina Sketch','variants'=>array('regular'),'subsets'=>array('latin')),
'Londrina_Solid'=>array('family'=>'Londrina Solid','variants'=>array('regular'),'subsets'=>array('latin')),
'Lora'=>array('family'=>'Lora','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Love_Ya_Like_A_Sister'=>array('family'=>'Love Ya Like A Sister','variants'=>array('regular'),'subsets'=>array('latin')),
'Loved_by_the_King'=>array('family'=>'Loved by the King','variants'=>array('regular'),'subsets'=>array('latin')),
'Lovers_Quarrel'=>array('family'=>'Lovers Quarrel','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Luckiest_Guy'=>array('family'=>'Luckiest Guy','variants'=>array('regular'),'subsets'=>array('latin')),
'Lusitana'=>array('family'=>'Lusitana','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Lustria'=>array('family'=>'Lustria','variants'=>array('regular'),'subsets'=>array('latin')),
'Macondo'=>array('family'=>'Macondo','variants'=>array('regular'),'subsets'=>array('latin')),
'Macondo_Swash_Caps'=>array('family'=>'Macondo Swash Caps','variants'=>array('regular'),'subsets'=>array('latin')),
'Magra'=>array('family'=>'Magra','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Maiden_Orange'=>array('family'=>'Maiden Orange','variants'=>array('regular'),'subsets'=>array('latin')),
'Mako'=>array('family'=>'Mako','variants'=>array('regular'),'subsets'=>array('latin')),
'Marcellus'=>array('family'=>'Marcellus','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Marcellus_SC'=>array('family'=>'Marcellus SC','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Marck_Script'=>array('family'=>'Marck Script','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Margarine'=>array('family'=>'Margarine','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Marko_One'=>array('family'=>'Marko One','variants'=>array('regular'),'subsets'=>array('latin')),
'Marmelad'=>array('family'=>'Marmelad','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Marvel'=>array('family'=>'Marvel','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Mate'=>array('family'=>'Mate','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'Mate_SC'=>array('family'=>'Mate SC','variants'=>array('regular'),'subsets'=>array('latin')),
'Maven_Pro'=>array('family'=>'Maven Pro','variants'=>array('regular','500','700','900'),'subsets'=>array('latin')),
'McLaren'=>array('family'=>'McLaren','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Meddon'=>array('family'=>'Meddon','variants'=>array('regular'),'subsets'=>array('latin')),
'MedievalSharp'=>array('family'=>'MedievalSharp','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Medula_One'=>array('family'=>'Medula One','variants'=>array('regular'),'subsets'=>array('latin')),
'Megrim'=>array('family'=>'Megrim','variants'=>array('regular'),'subsets'=>array('latin')),
'Meie_Script'=>array('family'=>'Meie Script','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Merienda'=>array('family'=>'Merienda','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Merienda_One'=>array('family'=>'Merienda One','variants'=>array('regular'),'subsets'=>array('latin')),
'Merriweather'=>array('family'=>'Merriweather','variants'=>array('300','300italic','regular','italic','700','700italic','900','900italic'),'subsets'=>array('latin-ext','latin')),
'Merriweather_Sans'=>array('family'=>'Merriweather Sans','variants'=>array('300','300italic','regular','italic','700','700italic','800','800italic'),'subsets'=>array('latin-ext','latin')),
'Metal'=>array('family'=>'Metal','variants'=>array('regular'),'subsets'=>array('khmer')),
'Metal_Mania'=>array('family'=>'Metal Mania','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Metamorphous'=>array('family'=>'Metamorphous','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Metrophobic'=>array('family'=>'Metrophobic','variants'=>array('regular'),'subsets'=>array('latin')),
'Michroma'=>array('family'=>'Michroma','variants'=>array('regular'),'subsets'=>array('latin')),
'Milonga'=>array('family'=>'Milonga','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Miltonian'=>array('family'=>'Miltonian','variants'=>array('regular'),'subsets'=>array('latin')),
'Miltonian_Tattoo'=>array('family'=>'Miltonian Tattoo','variants'=>array('regular'),'subsets'=>array('latin')),
'Miniver'=>array('family'=>'Miniver','variants'=>array('regular'),'subsets'=>array('latin')),
'Miss_Fajardose'=>array('family'=>'Miss Fajardose','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Modern_Antiqua'=>array('family'=>'Modern Antiqua','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Molengo'=>array('family'=>'Molengo','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Molle'=>array('family'=>'Molle','variants'=>array('italic'),'subsets'=>array('latin-ext','latin')),
'Monda'=>array('family'=>'Monda','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Monofett'=>array('family'=>'Monofett','variants'=>array('regular'),'subsets'=>array('latin')),
'Monoton'=>array('family'=>'Monoton','variants'=>array('regular'),'subsets'=>array('latin')),
'Monsieur_La_Doulaise'=>array('family'=>'Monsieur La Doulaise','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Montaga'=>array('family'=>'Montaga','variants'=>array('regular'),'subsets'=>array('latin')),
'Montez'=>array('family'=>'Montez','variants'=>array('regular'),'subsets'=>array('latin')),
'Montserrat'=>array('family'=>'Montserrat','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Montserrat_Alternates'=>array('family'=>'Montserrat Alternates','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Montserrat_Subrayada'=>array('family'=>'Montserrat Subrayada','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Moul'=>array('family'=>'Moul','variants'=>array('regular'),'subsets'=>array('khmer')),
'Moulpali'=>array('family'=>'Moulpali','variants'=>array('regular'),'subsets'=>array('khmer')),
'Mountains_of_Christmas'=>array('family'=>'Mountains of Christmas','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Mouse_Memoirs'=>array('family'=>'Mouse Memoirs','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Mr_Bedfort'=>array('family'=>'Mr Bedfort','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Mr_Dafoe'=>array('family'=>'Mr Dafoe','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Mr_De_Haviland'=>array('family'=>'Mr De Haviland','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Mrs_Saint_Delafield'=>array('family'=>'Mrs Saint Delafield','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Mrs_Sheppards'=>array('family'=>'Mrs Sheppards','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Muli'=>array('family'=>'Muli','variants'=>array('300','300italic','regular','italic'),'subsets'=>array('latin')),
'Mystery_Quest'=>array('family'=>'Mystery Quest','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Neucha'=>array('family'=>'Neucha','variants'=>array('regular'),'subsets'=>array('cyrillic','latin')),
'Neuton'=>array('family'=>'Neuton','variants'=>array('200','300','regular','italic','700','800'),'subsets'=>array('latin-ext','latin')),
'New_Rocker'=>array('family'=>'New Rocker','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'News_Cycle'=>array('family'=>'News Cycle','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Niconne'=>array('family'=>'Niconne','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Nixie_One'=>array('family'=>'Nixie One','variants'=>array('regular'),'subsets'=>array('latin')),
'Nobile'=>array('family'=>'Nobile','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Nokora'=>array('family'=>'Nokora','variants'=>array('regular','700'),'subsets'=>array('khmer')),
'Norican'=>array('family'=>'Norican','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Nosifer'=>array('family'=>'Nosifer','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Nothing_You_Could_Do'=>array('family'=>'Nothing You Could Do','variants'=>array('regular'),'subsets'=>array('latin')),
'Noticia_Text'=>array('family'=>'Noticia Text','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('vietnamese','latin-ext','latin')),
'Noto_Sans'=>array('family'=>'Noto Sans','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','devanagari','cyrillic','greek-ext','latin')),
'Noto_Serif'=>array('family'=>'Noto Serif','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Nova_Cut'=>array('family'=>'Nova Cut','variants'=>array('regular'),'subsets'=>array('latin')),
'Nova_Flat'=>array('family'=>'Nova Flat','variants'=>array('regular'),'subsets'=>array('latin')),
'Nova_Mono'=>array('family'=>'Nova Mono','variants'=>array('regular'),'subsets'=>array('greek','latin')),
'Nova_Oval'=>array('family'=>'Nova Oval','variants'=>array('regular'),'subsets'=>array('latin')),
'Nova_Round'=>array('family'=>'Nova Round','variants'=>array('regular'),'subsets'=>array('latin')),
'Nova_Script'=>array('family'=>'Nova Script','variants'=>array('regular'),'subsets'=>array('latin')),
'Nova_Slim'=>array('family'=>'Nova Slim','variants'=>array('regular'),'subsets'=>array('latin')),
'Nova_Square'=>array('family'=>'Nova Square','variants'=>array('regular'),'subsets'=>array('latin')),
'Numans'=>array('family'=>'Numans','variants'=>array('regular'),'subsets'=>array('latin')),
'Nunito'=>array('family'=>'Nunito','variants'=>array('300','regular','700'),'subsets'=>array('latin')),
'Odor_Mean_Chey'=>array('family'=>'Odor Mean Chey','variants'=>array('regular'),'subsets'=>array('khmer')),
'Offside'=>array('family'=>'Offside','variants'=>array('regular'),'subsets'=>array('latin')),
'Old_Standard_TT'=>array('family'=>'Old Standard TT','variants'=>array('regular','italic','700'),'subsets'=>array('latin')),
'Oldenburg'=>array('family'=>'Oldenburg','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Oleo_Script'=>array('family'=>'Oleo Script','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Oleo_Script_Swash_Caps'=>array('family'=>'Oleo Script Swash Caps','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Open_Sans'=>array('family'=>'Open Sans','variants'=>array('300','300italic','regular','italic','600','600italic','700','700italic','800','800italic'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','devanagari','cyrillic','greek-ext','latin')),
'Open_Sans_Condensed'=>array('family'=>'Open Sans Condensed','variants'=>array('300','300italic','700'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Oranienbaum'=>array('family'=>'Oranienbaum','variants'=>array('regular'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'Orbitron'=>array('family'=>'Orbitron','variants'=>array('regular','500','700','900'),'subsets'=>array('latin')),
'Oregano'=>array('family'=>'Oregano','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Orienta'=>array('family'=>'Orienta','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Original_Surfer'=>array('family'=>'Original Surfer','variants'=>array('regular'),'subsets'=>array('latin')),
'Oswald'=>array('family'=>'Oswald','variants'=>array('300','regular','700'),'subsets'=>array('latin-ext','latin')),
'Over_the_Rainbow'=>array('family'=>'Over the Rainbow','variants'=>array('regular'),'subsets'=>array('latin')),
'Overlock'=>array('family'=>'Overlock','variants'=>array('regular','italic','700','700italic','900','900italic'),'subsets'=>array('latin-ext','latin')),
'Overlock_SC'=>array('family'=>'Overlock SC','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ovo'=>array('family'=>'Ovo','variants'=>array('regular'),'subsets'=>array('latin')),
'Oxygen'=>array('family'=>'Oxygen','variants'=>array('300','regular','700'),'subsets'=>array('latin-ext','latin')),
'Oxygen_Mono'=>array('family'=>'Oxygen Mono','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'PT_Mono'=>array('family'=>'PT Mono','variants'=>array('regular'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'PT_Sans'=>array('family'=>'PT Sans','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'PT_Sans_Caption'=>array('family'=>'PT Sans Caption','variants'=>array('regular','700'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'PT_Sans_Narrow'=>array('family'=>'PT Sans Narrow','variants'=>array('regular','700'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'PT_Serif'=>array('family'=>'PT Serif','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'PT_Serif_Caption'=>array('family'=>'PT Serif Caption','variants'=>array('regular','italic'),'subsets'=>array('cyrillic-ext','latin-ext','cyrillic','latin')),
'Pacifico'=>array('family'=>'Pacifico','variants'=>array('regular'),'subsets'=>array('latin')),
'Paprika'=>array('family'=>'Paprika','variants'=>array('regular'),'subsets'=>array('latin')),
'Parisienne'=>array('family'=>'Parisienne','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Passero_One'=>array('family'=>'Passero One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Passion_One'=>array('family'=>'Passion One','variants'=>array('regular','700','900'),'subsets'=>array('latin-ext','latin')),
'Pathway_Gothic_One'=>array('family'=>'Pathway Gothic One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Patrick_Hand'=>array('family'=>'Patrick Hand','variants'=>array('regular'),'subsets'=>array('vietnamese','latin-ext','latin')),
'Patrick_Hand_SC'=>array('family'=>'Patrick Hand SC','variants'=>array('regular'),'subsets'=>array('vietnamese','latin-ext','latin')),
'Patua_One'=>array('family'=>'Patua One','variants'=>array('regular'),'subsets'=>array('latin')),
'Paytone_One'=>array('family'=>'Paytone One','variants'=>array('regular'),'subsets'=>array('latin')),
'Peralta'=>array('family'=>'Peralta','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Permanent_Marker'=>array('family'=>'Permanent Marker','variants'=>array('regular'),'subsets'=>array('latin')),
'Petit_Formal_Script'=>array('family'=>'Petit Formal Script','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Petrona'=>array('family'=>'Petrona','variants'=>array('regular'),'subsets'=>array('latin')),
'Philosopher'=>array('family'=>'Philosopher','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('cyrillic','latin')),
'Piedra'=>array('family'=>'Piedra','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Pinyon_Script'=>array('family'=>'Pinyon Script','variants'=>array('regular'),'subsets'=>array('latin')),
'Pirata_One'=>array('family'=>'Pirata One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Plaster'=>array('family'=>'Plaster','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Play'=>array('family'=>'Play','variants'=>array('regular','700'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','latin')),
'Playball'=>array('family'=>'Playball','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Playfair_Display'=>array('family'=>'Playfair Display','variants'=>array('regular','italic','700','700italic','900','900italic'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Playfair_Display_SC'=>array('family'=>'Playfair Display SC','variants'=>array('regular','italic','700','700italic','900','900italic'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Podkova'=>array('family'=>'Podkova','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Poiret_One'=>array('family'=>'Poiret One','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Poller_One'=>array('family'=>'Poller One','variants'=>array('regular'),'subsets'=>array('latin')),
'Poly'=>array('family'=>'Poly','variants'=>array('regular','italic'),'subsets'=>array('latin')),
'Pompiere'=>array('family'=>'Pompiere','variants'=>array('regular'),'subsets'=>array('latin')),
'Pontano_Sans'=>array('family'=>'Pontano Sans','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Port_Lligat_Sans'=>array('family'=>'Port Lligat Sans','variants'=>array('regular'),'subsets'=>array('latin')),
'Port_Lligat_Slab'=>array('family'=>'Port Lligat Slab','variants'=>array('regular'),'subsets'=>array('latin')),
'Prata'=>array('family'=>'Prata','variants'=>array('regular'),'subsets'=>array('latin')),
'Preahvihear'=>array('family'=>'Preahvihear','variants'=>array('regular'),'subsets'=>array('khmer')),
'Press_Start_2P'=>array('family'=>'Press Start 2P','variants'=>array('regular'),'subsets'=>array('latin-ext','greek','cyrillic','latin')),
'Princess_Sofia'=>array('family'=>'Princess Sofia','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Prociono'=>array('family'=>'Prociono','variants'=>array('regular'),'subsets'=>array('latin')),
'Prosto_One'=>array('family'=>'Prosto One','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Puritan'=>array('family'=>'Puritan','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Purple_Purse'=>array('family'=>'Purple Purse','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Quando'=>array('family'=>'Quando','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Quantico'=>array('family'=>'Quantico','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Quattrocento'=>array('family'=>'Quattrocento','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Quattrocento_Sans'=>array('family'=>'Quattrocento Sans','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Questrial'=>array('family'=>'Questrial','variants'=>array('regular'),'subsets'=>array('latin')),
'Quicksand'=>array('family'=>'Quicksand','variants'=>array('300','regular','700'),'subsets'=>array('latin')),
'Quintessential'=>array('family'=>'Quintessential','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Qwigley'=>array('family'=>'Qwigley','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Racing_Sans_One'=>array('family'=>'Racing Sans One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Radley'=>array('family'=>'Radley','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Rajdhani'=>array('family'=>'Rajdhani','variants'=>array('300','regular','500','600','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Raleway'=>array('family'=>'Raleway','variants'=>array('100','200','300','regular','500','600','700','800','900'),'subsets'=>array('latin')),
'Raleway_Dots'=>array('family'=>'Raleway Dots','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Rambla'=>array('family'=>'Rambla','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Rammetto_One'=>array('family'=>'Rammetto One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ranchers'=>array('family'=>'Ranchers','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Rancho'=>array('family'=>'Rancho','variants'=>array('regular'),'subsets'=>array('latin')),
'Rationale'=>array('family'=>'Rationale','variants'=>array('regular'),'subsets'=>array('latin')),
'Redressed'=>array('family'=>'Redressed','variants'=>array('regular'),'subsets'=>array('latin')),
'Reenie_Beanie'=>array('family'=>'Reenie Beanie','variants'=>array('regular'),'subsets'=>array('latin')),
'Revalia'=>array('family'=>'Revalia','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ribeye'=>array('family'=>'Ribeye','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ribeye_Marrow'=>array('family'=>'Ribeye Marrow','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Righteous'=>array('family'=>'Righteous','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Risque'=>array('family'=>'Risque','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Roboto'=>array('family'=>'Roboto','variants'=>array('100','100italic','300','300italic','regular','italic','500','500italic','700','700italic','900','900italic'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Roboto_Condensed'=>array('family'=>'Roboto Condensed','variants'=>array('300','300italic','regular','italic','700','700italic'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Roboto_Slab'=>array('family'=>'Roboto Slab','variants'=>array('100','300','regular','700'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Rochester'=>array('family'=>'Rochester','variants'=>array('regular'),'subsets'=>array('latin')),
'Rock_Salt'=>array('family'=>'Rock Salt','variants'=>array('regular'),'subsets'=>array('latin')),
'Rokkitt'=>array('family'=>'Rokkitt','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Romanesco'=>array('family'=>'Romanesco','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ropa_Sans'=>array('family'=>'Ropa Sans','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Rosario'=>array('family'=>'Rosario','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Rosarivo'=>array('family'=>'Rosarivo','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Rouge_Script'=>array('family'=>'Rouge Script','variants'=>array('regular'),'subsets'=>array('latin')),
'Rozha_One'=>array('family'=>'Rozha One','variants'=>array('regular'),'subsets'=>array('latin-ext','devanagari','latin')),
'Rubik_Mono_One'=>array('family'=>'Rubik Mono One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Rubik_One'=>array('family'=>'Rubik One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ruda'=>array('family'=>'Ruda','variants'=>array('regular','700','900'),'subsets'=>array('latin-ext','latin')),
'Rufina'=>array('family'=>'Rufina','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Ruge_Boogie'=>array('family'=>'Ruge Boogie','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ruluko'=>array('family'=>'Ruluko','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Rum_Raisin'=>array('family'=>'Rum Raisin','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Ruslan_Display'=>array('family'=>'Ruslan Display','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Russo_One'=>array('family'=>'Russo One','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Ruthie'=>array('family'=>'Ruthie','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Rye'=>array('family'=>'Rye','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Sacramento'=>array('family'=>'Sacramento','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Sail'=>array('family'=>'Sail','variants'=>array('regular'),'subsets'=>array('latin')),
'Salsa'=>array('family'=>'Salsa','variants'=>array('regular'),'subsets'=>array('latin')),
'Sanchez'=>array('family'=>'Sanchez','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Sancreek'=>array('family'=>'Sancreek','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Sansita_One'=>array('family'=>'Sansita One','variants'=>array('regular'),'subsets'=>array('latin')),
'Sarina'=>array('family'=>'Sarina','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Sarpanch'=>array('family'=>'Sarpanch','variants'=>array('regular','500','600','700','800','900'),'subsets'=>array('latin-ext','devanagari','latin')),
'Satisfy'=>array('family'=>'Satisfy','variants'=>array('regular'),'subsets'=>array('latin')),
'Scada'=>array('family'=>'Scada','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Schoolbell'=>array('family'=>'Schoolbell','variants'=>array('regular'),'subsets'=>array('latin')),
'Seaweed_Script'=>array('family'=>'Seaweed Script','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Sevillana'=>array('family'=>'Sevillana','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Seymour_One'=>array('family'=>'Seymour One','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Shadows_Into_Light'=>array('family'=>'Shadows Into Light','variants'=>array('regular'),'subsets'=>array('latin')),
'Shadows_Into_Light_Two'=>array('family'=>'Shadows Into Light Two','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Shanti'=>array('family'=>'Shanti','variants'=>array('regular'),'subsets'=>array('latin')),
'Share'=>array('family'=>'Share','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin-ext','latin')),
'Share_Tech'=>array('family'=>'Share Tech','variants'=>array('regular'),'subsets'=>array('latin')),
'Share_Tech_Mono'=>array('family'=>'Share Tech Mono','variants'=>array('regular'),'subsets'=>array('latin')),
'Shojumaru'=>array('family'=>'Shojumaru','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Short_Stack'=>array('family'=>'Short Stack','variants'=>array('regular'),'subsets'=>array('latin')),
'Siemreap'=>array('family'=>'Siemreap','variants'=>array('regular'),'subsets'=>array('khmer')),
'Sigmar_One'=>array('family'=>'Sigmar One','variants'=>array('regular'),'subsets'=>array('latin')),
'Signika'=>array('family'=>'Signika','variants'=>array('300','regular','600','700'),'subsets'=>array('latin-ext','latin')),
'Signika_Negative'=>array('family'=>'Signika Negative','variants'=>array('300','regular','600','700'),'subsets'=>array('latin-ext','latin')),
'Simonetta'=>array('family'=>'Simonetta','variants'=>array('regular','italic','900','900italic'),'subsets'=>array('latin-ext','latin')),
'Sintony'=>array('family'=>'Sintony','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Sirin_Stencil'=>array('family'=>'Sirin Stencil','variants'=>array('regular'),'subsets'=>array('latin')),
'Six_Caps'=>array('family'=>'Six Caps','variants'=>array('regular'),'subsets'=>array('latin')),
'Skranji'=>array('family'=>'Skranji','variants'=>array('regular','700'),'subsets'=>array('latin-ext','latin')),
'Slabo_13px'=>array('family'=>'Slabo 13px','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Slabo_27px'=>array('family'=>'Slabo 27px','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Slackey'=>array('family'=>'Slackey','variants'=>array('regular'),'subsets'=>array('latin')),
'Smokum'=>array('family'=>'Smokum','variants'=>array('regular'),'subsets'=>array('latin')),
'Smythe'=>array('family'=>'Smythe','variants'=>array('regular'),'subsets'=>array('latin')),
'Sniglet'=>array('family'=>'Sniglet','variants'=>array('regular','800'),'subsets'=>array('latin-ext','latin')),
'Snippet'=>array('family'=>'Snippet','variants'=>array('regular'),'subsets'=>array('latin')),
'Snowburst_One'=>array('family'=>'Snowburst One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Sofadi_One'=>array('family'=>'Sofadi One','variants'=>array('regular'),'subsets'=>array('latin')),
'Sofia'=>array('family'=>'Sofia','variants'=>array('regular'),'subsets'=>array('latin')),
'Sonsie_One'=>array('family'=>'Sonsie One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Sorts_Mill_Goudy'=>array('family'=>'Sorts Mill Goudy','variants'=>array('regular','italic'),'subsets'=>array('latin-ext','latin')),
'Source_Code_Pro'=>array('family'=>'Source Code Pro','variants'=>array('200','300','regular','500','600','700','900'),'subsets'=>array('latin-ext','latin')),
'Source_Sans_Pro'=>array('family'=>'Source Sans Pro','variants'=>array('200','200italic','300','300italic','regular','italic','600','600italic','700','700italic','900','900italic'),'subsets'=>array('vietnamese','latin-ext','latin')),
'Source_Serif_Pro'=>array('family'=>'Source Serif Pro','variants'=>array('regular','600','700'),'subsets'=>array('latin-ext','latin')),
'Special_Elite'=>array('family'=>'Special Elite','variants'=>array('regular'),'subsets'=>array('latin')),
'Spicy_Rice'=>array('family'=>'Spicy Rice','variants'=>array('regular'),'subsets'=>array('latin')),
'Spinnaker'=>array('family'=>'Spinnaker','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Spirax'=>array('family'=>'Spirax','variants'=>array('regular'),'subsets'=>array('latin')),
'Squada_One'=>array('family'=>'Squada One','variants'=>array('regular'),'subsets'=>array('latin')),
'Stalemate'=>array('family'=>'Stalemate','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Stalinist_One'=>array('family'=>'Stalinist One','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Stardos_Stencil'=>array('family'=>'Stardos Stencil','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Stint_Ultra_Condensed'=>array('family'=>'Stint Ultra Condensed','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Stint_Ultra_Expanded'=>array('family'=>'Stint Ultra Expanded','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Stoke'=>array('family'=>'Stoke','variants'=>array('300','regular'),'subsets'=>array('latin-ext','latin')),
'Strait'=>array('family'=>'Strait','variants'=>array('regular'),'subsets'=>array('latin')),
'Sue_Ellen_Francisco'=>array('family'=>'Sue Ellen Francisco','variants'=>array('regular'),'subsets'=>array('latin')),
'Sunshiney'=>array('family'=>'Sunshiney','variants'=>array('regular'),'subsets'=>array('latin')),
'Supermercado_One'=>array('family'=>'Supermercado One','variants'=>array('regular'),'subsets'=>array('latin')),
'Suwannaphum'=>array('family'=>'Suwannaphum','variants'=>array('regular'),'subsets'=>array('khmer')),
'Swanky_and_Moo_Moo'=>array('family'=>'Swanky and Moo Moo','variants'=>array('regular'),'subsets'=>array('latin')),
'Syncopate'=>array('family'=>'Syncopate','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Tangerine'=>array('family'=>'Tangerine','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Taprom'=>array('family'=>'Taprom','variants'=>array('regular'),'subsets'=>array('khmer')),
'Tauri'=>array('family'=>'Tauri','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Teko'=>array('family'=>'Teko','variants'=>array('300','regular','500','600','700'),'subsets'=>array('latin-ext','devanagari','latin')),
'Telex'=>array('family'=>'Telex','variants'=>array('regular'),'subsets'=>array('latin')),
'Tenor_Sans'=>array('family'=>'Tenor Sans','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Text_Me_One'=>array('family'=>'Text Me One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'The_Girl_Next_Door'=>array('family'=>'The Girl Next Door','variants'=>array('regular'),'subsets'=>array('latin')),
'Tienne'=>array('family'=>'Tienne','variants'=>array('regular','700','900'),'subsets'=>array('latin')),
'Tinos'=>array('family'=>'Tinos','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('vietnamese','cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Titan_One'=>array('family'=>'Titan One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Titillium_Web'=>array('family'=>'Titillium Web','variants'=>array('200','200italic','300','300italic','regular','italic','600','600italic','700','700italic','900'),'subsets'=>array('latin-ext','latin')),
'Trade_Winds'=>array('family'=>'Trade Winds','variants'=>array('regular'),'subsets'=>array('latin')),
'Trocchi'=>array('family'=>'Trocchi','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Trochut'=>array('family'=>'Trochut','variants'=>array('regular','italic','700'),'subsets'=>array('latin')),
'Trykker'=>array('family'=>'Trykker','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Tulpen_One'=>array('family'=>'Tulpen One','variants'=>array('regular'),'subsets'=>array('latin')),
'Ubuntu'=>array('family'=>'Ubuntu','variants'=>array('300','300italic','regular','italic','500','500italic','700','700italic'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Ubuntu_Condensed'=>array('family'=>'Ubuntu Condensed','variants'=>array('regular'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Ubuntu_Mono'=>array('family'=>'Ubuntu Mono','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('cyrillic-ext','latin-ext','greek','cyrillic','greek-ext','latin')),
'Ultra'=>array('family'=>'Ultra','variants'=>array('regular'),'subsets'=>array('latin')),
'Uncial_Antiqua'=>array('family'=>'Uncial Antiqua','variants'=>array('regular'),'subsets'=>array('latin')),
'Underdog'=>array('family'=>'Underdog','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Unica_One'=>array('family'=>'Unica One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'UnifrakturCook'=>array('family'=>'UnifrakturCook','variants'=>array('700'),'subsets'=>array('latin')),
'UnifrakturMaguntia'=>array('family'=>'UnifrakturMaguntia','variants'=>array('regular'),'subsets'=>array('latin')),
'Unkempt'=>array('family'=>'Unkempt','variants'=>array('regular','700'),'subsets'=>array('latin')),
'Unlock'=>array('family'=>'Unlock','variants'=>array('regular'),'subsets'=>array('latin')),
'Unna'=>array('family'=>'Unna','variants'=>array('regular'),'subsets'=>array('latin')),
'VT323'=>array('family'=>'VT323','variants'=>array('regular'),'subsets'=>array('latin')),
'Vampiro_One'=>array('family'=>'Vampiro One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Varela'=>array('family'=>'Varela','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Varela_Round'=>array('family'=>'Varela Round','variants'=>array('regular'),'subsets'=>array('latin')),
'Vast_Shadow'=>array('family'=>'Vast Shadow','variants'=>array('regular'),'subsets'=>array('latin')),
'Vesper_Libre'=>array('family'=>'Vesper Libre','variants'=>array('regular','500','700','900'),'subsets'=>array('latin-ext','devanagari','latin')),
'Vibur'=>array('family'=>'Vibur','variants'=>array('regular'),'subsets'=>array('latin')),
'Vidaloka'=>array('family'=>'Vidaloka','variants'=>array('regular'),'subsets'=>array('latin')),
'Viga'=>array('family'=>'Viga','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Voces'=>array('family'=>'Voces','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Volkhov'=>array('family'=>'Volkhov','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Vollkorn'=>array('family'=>'Vollkorn','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('latin')),
'Voltaire'=>array('family'=>'Voltaire','variants'=>array('regular'),'subsets'=>array('latin')),
'Waiting_for_the_Sunrise'=>array('family'=>'Waiting for the Sunrise','variants'=>array('regular'),'subsets'=>array('latin')),
'Wallpoet'=>array('family'=>'Wallpoet','variants'=>array('regular'),'subsets'=>array('latin')),
'Walter_Turncoat'=>array('family'=>'Walter Turncoat','variants'=>array('regular'),'subsets'=>array('latin')),
'Warnes'=>array('family'=>'Warnes','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Wellfleet'=>array('family'=>'Wellfleet','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Wendy_One'=>array('family'=>'Wendy One','variants'=>array('regular'),'subsets'=>array('latin-ext','latin')),
'Wire_One'=>array('family'=>'Wire One','variants'=>array('regular'),'subsets'=>array('latin')),
'Yanone_Kaffeesatz'=>array('family'=>'Yanone Kaffeesatz','variants'=>array('200','300','regular','700'),'subsets'=>array('latin-ext','latin')),
'Yellowtail'=>array('family'=>'Yellowtail','variants'=>array('regular'),'subsets'=>array('latin')),
'Yeseva_One'=>array('family'=>'Yeseva One','variants'=>array('regular'),'subsets'=>array('latin-ext','cyrillic','latin')),
'Yesteryear'=>array('family'=>'Yesteryear','variants'=>array('regular'),'subsets'=>array('latin')),
'Zeyada'=>array('family'=>'Zeyada','variants'=>array('regular'),'subsets'=>array('latin')),
'Lateef'=>array('family'=>'Lateef','variants'=>array('regular'),'subsets'=>array('arabic','latin')),
'Amiri'=>array('family'=>'Amiri','variants'=>array('regular','italic','700','700italic'),'subsets'=>array('arabic','latin')),
'Scheherazade'=>array('family'=>'Scheherazade','variants'=>array('regular','700'),'subsets'=>array('arabic','latin')),
);
?>